# Generated by Django 5.0.4 on 2024-05-27 08:46

import ulid.api.api
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreai', '0005_alter_company_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='debt',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='financialinstitution',
            name='JBAcode',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='financialinstitution',
            name='bank_category',
            field=models.CharField(choices=[('都市銀行', '都市銀行'), ('地方銀行', '地方銀行'), ('第二地銀', '第二地銀'), ('信用金庫', '信用金庫'), ('信用組合', '信用組合'), ('信金中央金庫', '信金中央金庫'), ('政府関係機関', '政府関係機関'), ('商工組合中央金庫', '商工組合中央金庫'), ('全国信用協同組合連合会', '全国信用協同組合連合会'), ('労働金庫連合会', '労働金庫連合会'), ('農林中央金庫', '農林中央金庫'), ('信託銀行', '信託銀行'), ('その他金融機関', 'その他金融機関')], default='地方銀行', max_length=50),
        ),
        migrations.AlterField(
            model_name='firm',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='ユーザーがアクティブかどうかを指定しま。', verbose_name='アクティブ'),
        ),
        migrations.AlterField(
            model_name='usercompany',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
    ]
