# Generated by Django 5.0.4 on 2024-05-28 00:33

import django.core.validators
import django.db.models.deletion
import ulid.api.api
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreai', '0008_alter_company_id_alter_debt_id_alter_firm_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyRevenue',
            fields=[
                ('id', models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='年')),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='月')),
                ('sales', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='売上')),
                ('operating_profit', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='営業利益')),
                ('ordinary_profit', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='経常利益')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_revenues', to='scoreai.company')),
            ],
            options={
                'verbose_name': '月次売上',
                'verbose_name_plural': '月次売上',
                'unique_together': {('company', 'year', 'month')},
            },
        ),
    ]
