# Generated by Django 5.0.4 on 2024-05-28 01:14

import django.core.validators
import ulid.api.api
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreai', '0009_alter_company_id_alter_debt_id_alter_firm_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlyrevenue',
            options={'verbose_name': '月次PL', 'verbose_name_plural': '月次PL'},
        ),
        migrations.AddField(
            model_name='monthlyrevenue',
            name='gross_profit',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15, verbose_name='売上総利益（千円）'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='monthlyrevenue',
            name='month',
            field=models.IntegerField(help_text='決算月に関わらず1始まり12終わり', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='月度'),
        ),
        migrations.AlterField(
            model_name='monthlyrevenue',
            name='operating_profit',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='営業利益（千円）'),
        ),
        migrations.AlterField(
            model_name='monthlyrevenue',
            name='ordinary_profit',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='経常利益（千円）'),
        ),
        migrations.AlterField(
            model_name='monthlyrevenue',
            name='sales',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='売上（千円）'),
        ),
    ]
