# Generated by Django 5.0.4 on 2024-05-30 10:56

import ulid.api.api
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreai', '0010_alter_monthlyrevenue_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyrevenue',
            name='gross_profit',
            field=models.IntegerField(verbose_name='売上総利益（千円）'),
        ),
        migrations.AlterField(
            model_name='monthlyrevenue',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='monthlyrevenue',
            name='operating_profit',
            field=models.IntegerField(verbose_name='営業利益（千円）'),
        ),
        migrations.AlterField(
            model_name='monthlyrevenue',
            name='ordinary_profit',
            field=models.IntegerField(verbose_name='経常利益（千円）'),
        ),
        migrations.AlterField(
            model_name='monthlyrevenue',
            name='sales',
            field=models.IntegerField(verbose_name='売上（千円）'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='IF the user is Active or not.', verbose_name='アクティブ'),
        ),
    ]
