# Generated by Django 5.0.4 on 2024-06-04 01:32

import django.core.validators
import ulid.api.api
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreai', '0012_debt_payment_terms_alter_company_id_alter_debt_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecuredType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='保証区分')),
            ],
        ),
        migrations.AddField(
            model_name='debt',
            name='is_collateraled',
            field=models.BooleanField(default=False, verbose_name='担保'),
        ),
        migrations.AddField(
            model_name='debt',
            name='is_nodisplay',
            field=models.BooleanField(default=False, verbose_name='非表示'),
        ),
        migrations.AddField(
            model_name='debt',
            name='is_securedby_management',
            field=models.BooleanField(default=False, verbose_name='経営者保証'),
        ),
        migrations.AddField(
            model_name='debt',
            name='memo_long',
            field=models.TextField(blank=True, verbose_name='長文メモ'),
        ),
        migrations.AddField(
            model_name='debt',
            name='memo_short',
            field=models.CharField(blank=True, max_length=126, verbose_name='短文メモ'),
        ),
        migrations.AddField(
            model_name='debt',
            name='reschedule_balance',
            field=models.IntegerField(blank=True, null=True, verbose_name='リスケ時点の残高'),
        ),
        migrations.AddField(
            model_name='debt',
            name='reschedule_date',
            field=models.DateField(blank=True, null=True, verbose_name='リスケ日'),
        ),
        migrations.AlterField(
            model_name='monthlyrevenue',
            name='month',
            field=models.IntegerField(help_text='Always starting with 1, regardless of fiscal period.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='月度'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='IF the user is Active or not.', verbose_name='Active'),
        ),
    ]
