# Generated by Django 5.0.4 on 2024-09-20 23:08

import django.db.models.deletion
import ulid.api.api
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreai', '0014_debt_secured_type_alter_company_id_alter_debt_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='debt',
            name='adjusted_amount_first',
            field=models.IntegerField(default=0, help_text='単位：円。初月だけ返済額が異なる場合は通常月との差額を入力。差がなければゼロ。', verbose_name='初月調整額'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='adjusted_amount_last',
            field=models.IntegerField(default=0, help_text='単位：円。最終月だけ返済額が異なる場合は通常月との差額を入力。差がなければゼロ。', verbose_name='最終月調整額'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='financial_institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreai.financialinstitution', verbose_name='金融機関名'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='debt',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, help_text='単位：%', max_digits=4, verbose_name='利息'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='monthly_repayment',
            field=models.IntegerField(help_text='単位：円', verbose_name='月返済額'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='principal',
            field=models.IntegerField(help_text='単位：円', verbose_name='借入元本'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='secured_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreai.securedtype', verbose_name='保証協会'),
        ),
        migrations.AlterField(
            model_name='firm',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='monthlyrevenue',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usercompany',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='UserFirm',
            fields=[
                ('id', models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('is_selected', models.BooleanField(default=True)),
                ('is_owner', models.BooleanField(default=False)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_firms', to='scoreai.firm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_firms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
