# Generated by Django 5.0.4 on 2024-09-21 23:17

import django.db.models.deletion
import ulid.api.api
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreai', '0015_alter_company_id_alter_debt_adjusted_amount_first_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmCompany',
            fields=[
                ('id', models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('start_date', models.DateField(verbose_name='開始日')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='終了日')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firm_companies', to='scoreai.company')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firm_companies', to='scoreai.firm')),
            ],
            options={
                'verbose_name': '契約関係',
                'verbose_name_plural': '企業と事務所の関係',
                'unique_together': {('firm', 'company')},
            },
        ),
    ]
