# Generated by Django 5.0.4 on 2024-09-24 02:39

import django.core.validators
import django.db.models.deletion
import ulid.api.api
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreai', '0017_create_yearlyfiscalsummary'),
    ]

    operations = [

        migrations.AlterField(
            model_name='yearlyfiscalsummary',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='MonthlyFiscalSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(13)], verbose_name='月')),
                ('sales', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='売上高')),
                ('gross_profit', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='粗利益')),
                ('operating_profit', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='営業利益')),
                ('ordinary_profit', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='経常利益')),
                ('yearly_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_summaries', to='scoreai.yearlyfiscalsummary')),
            ],
            options={
                'verbose_name': '月次決算情報',
                'verbose_name_plural': '月次決算情報',
                'unique_together': {('yearly_summary', 'month')},
            },
        ),
    ]
