# Generated by Django 5.0.4 on 2024-09-24 03:02

import django.core.validators
import django.db.models.deletion
import ulid.api.api
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreai', '0019_delete_fiscalsummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='debt',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='firm',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='firmcompany',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usercompany',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userfirm',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='FiscalSummary_Year',
            fields=[
                ('id', models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='年')),
                ('version', models.IntegerField(default=1, verbose_name='バージョン')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_summary_years', to='scoreai.company')),
            ],
            options={
                'verbose_name': '年次決算情報',
                'verbose_name_plural': '年次決算情報',
                'unique_together': {('company', 'year', 'version')},
            },
        ),
        migrations.CreateModel(
            name='FiscalSummary_Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(13)], verbose_name='月度')),
                ('sales', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='売上高')),
                ('gross_profit', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='粗利益')),
                ('operating_profit', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='営業利益')),
                ('ordinary_profit', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='経常利益')),
                ('fiscal_summary_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_summaries', to='scoreai.fiscalsummary_year')),
            ],
            options={
                'verbose_name': '月次決算情報',
                'verbose_name_plural': '月次決算情報',
                'unique_together': {('fiscal_summary_year', 'period')},
            },
        ),
    ]
