# Generated by Django 5.0.4 on 2024-09-24 05:36

import ulid.api.api
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreai', '0020_create_fiscalsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='code',
            field=models.CharField(default=9999, max_length=20),
            preserve_default=False,
        ),
    ]
