# Generated by Django 5.0.4 on 2024-09-24 05:38

import ulid.api.api
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreai', '0021_company_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
