# Generated by Django 5.0.4 on 2024-09-24 08:35

import ulid.api.api
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreai', '0022_alter_company_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'ユーザー', 'verbose_name_plural': 'ユ��ザー'},
        ),
        migrations.AddField(
            model_name='fiscalsummary_year',
            name='capital_stock',
            field=models.IntegerField(default=0, verbose_name='資本金（千円）'),
        ),
        migrations.AddField(
            model_name='fiscalsummary_year',
            name='cash_and_deposits',
            field=models.IntegerField(default=0, verbose_name='現金及び預金（千円）'),
        ),
        migrations.AddField(
            model_name='fiscalsummary_year',
            name='depreciation_expense',
            field=models.IntegerField(default=0, verbose_name='減価償却額（販管費）（千円）'),
        ),
        migrations.AddField(
            model_name='fiscalsummary_year',
            name='directors_compensation',
            field=models.IntegerField(default=0, verbose_name='役員報酬（千円）'),
        ),
        migrations.AddField(
            model_name='fiscalsummary_year',
            name='financial_statement_notes',
            field=models.TextField(blank=True, verbose_name='決算留意事項'),
        ),
        migrations.AddField(
            model_name='fiscalsummary_year',
            name='income_taxes',
            field=models.IntegerField(default=0, verbose_name='法人税等（千円）'),
        ),
        migrations.AddField(
            model_name='fiscalsummary_year',
            name='long_term_loans_payable',
            field=models.IntegerField(default=0, verbose_name='長期借入金（千円）'),
        ),
        migrations.AddField(
            model_name='fiscalsummary_year',
            name='non_operating_amortization_expense',
            field=models.IntegerField(default=0, verbose_name='営業外で計上された償却費（千円）'),
        ),
        migrations.AddField(
            model_name='fiscalsummary_year',
            name='other_amortization_expense',
            field=models.IntegerField(default=0, verbose_name='その他の償却額（販管費）（千円）'),
        ),
        migrations.AddField(
            model_name='fiscalsummary_year',
            name='retained_earnings',
            field=models.IntegerField(default=0, verbose_name='繰越利益剰余金（千円）'),
        ),
        migrations.AddField(
            model_name='fiscalsummary_year',
            name='salaries_and_other_personnel_expenses',
            field=models.IntegerField(default=0, verbose_name='給料・雑給・その他人件費（千円）'),
        ),
        migrations.AddField(
            model_name='fiscalsummary_year',
            name='short_term_loans_payable',
            field=models.IntegerField(default=0, verbose_name='短期借入金（千円）'),
        ),
        migrations.AddField(
            model_name='fiscalsummary_year',
            name='tax_loss_carryforward',
            field=models.IntegerField(default=0, verbose_name='繰越欠損金（千円）'),
        ),
        migrations.AddField(
            model_name='fiscalsummary_year',
            name='total_assets',
            field=models.IntegerField(default=0, verbose_name='資産の部合計（千円）'),
        ),
        migrations.AddField(
            model_name='fiscalsummary_year',
            name='total_current_assets',
            field=models.IntegerField(default=0, verbose_name='流動資産合計（千円）'),
        ),
        migrations.AddField(
            model_name='fiscalsummary_year',
            name='total_current_liabilities',
            field=models.IntegerField(default=0, verbose_name='流動負債合計（千円）'),
        ),
        migrations.AddField(
            model_name='fiscalsummary_year',
            name='total_fixed_assets',
            field=models.IntegerField(default=0, verbose_name='固定資産合計（千円）'),
        ),
        migrations.AddField(
            model_name='fiscalsummary_year',
            name='total_liabilities',
            field=models.IntegerField(default=0, verbose_name='負債の部合計（千円）'),
        ),
        migrations.AddField(
            model_name='fiscalsummary_year',
            name='total_net_assets',
            field=models.IntegerField(default=0, verbose_name='純資産の部合計（千円）'),
        ),
        migrations.AddField(
            model_name='fiscalsummary_year',
            name='total_tangible_fixed_assets',
            field=models.IntegerField(default=0, verbose_name='有形固定資産合計（千円）'),
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='debt',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='firm',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='firmcompany',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fiscalsummary_year',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usercompany',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userfirm',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
    ]
