# Generated by Django 5.0.4 on 2024-10-01 07:37

import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import ulid.api.api
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scoreai', '0024_alter_meeting_minutes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'ユーザー', 'verbose_name_plural': 'ユーザー'},
        ),
        migrations.RenameField(
            model_name='meetingminutes',
            old_name='date',
            new_name='meeting_date',
        ),
        migrations.AddField(
            model_name='fiscalsummary_year',
            name='accounts_payable',
            field=models.IntegerField(default=0, verbose_name='買掛金・未払金・未払費用（千円）'),
        ),
        migrations.AddField(
            model_name='fiscalsummary_year',
            name='accounts_receivable',
            field=models.IntegerField(default=0, verbose_name='売掛金（千円）'),
        ),
        migrations.AddField(
            model_name='fiscalsummary_year',
            name='buildings',
            field=models.IntegerField(default=0, verbose_name='建物及び附属設備（千円）'),
        ),
        migrations.AddField(
            model_name='fiscalsummary_year',
            name='capital_reserve',
            field=models.IntegerField(default=0, verbose_name='資本準備金（千円）'),
        ),
        migrations.AddField(
            model_name='fiscalsummary_year',
            name='deferred_assets',
            field=models.IntegerField(default=0, verbose_name='繰延資産（千円）'),
        ),
        migrations.AddField(
            model_name='fiscalsummary_year',
            name='depreciation_cogs',
            field=models.IntegerField(default=0, verbose_name='減価償却費（売上原価）（千円）'),
        ),
        migrations.AddField(
            model_name='fiscalsummary_year',
            name='directors_loan',
            field=models.IntegerField(default=0, help_text='貸付ならプラス、借入ならマイナス', verbose_name='役員貸付・借入金（千円）'),
        ),
        migrations.AddField(
            model_name='fiscalsummary_year',
            name='extraordinary_loss',
            field=models.IntegerField(default=0, verbose_name='特別損失（千円）'),
        ),
        migrations.AddField(
            model_name='fiscalsummary_year',
            name='extraordinary_profit',
            field=models.IntegerField(default=0, verbose_name='特別利益（千円）'),
        ),
        migrations.AddField(
            model_name='fiscalsummary_year',
            name='goodwill',
            field=models.IntegerField(default=0, verbose_name='無形固定資産（千円）'),
        ),
        migrations.AddField(
            model_name='fiscalsummary_year',
            name='gross_profit',
            field=models.IntegerField(default=0, verbose_name='粗利益（千円）'),
        ),
        migrations.AddField(
            model_name='fiscalsummary_year',
            name='inventory',
            field=models.IntegerField(default=0, verbose_name='棚卸資産（千円）'),
        ),
        migrations.AddField(
            model_name='fiscalsummary_year',
            name='issued_shares_EOY',
            field=models.IntegerField(default=0, verbose_name='期末発行済み株式数（株）'),
        ),
        migrations.AddField(
            model_name='fiscalsummary_year',
            name='land',
            field=models.IntegerField(default=0, verbose_name='土地（千円）'),
        ),
        migrations.AddField(
            model_name='fiscalsummary_year',
            name='machinery_equipment',
            field=models.IntegerField(default=0, verbose_name='機械及び装置（千円）'),
        ),
        migrations.AddField(
            model_name='fiscalsummary_year',
            name='net_profit',
            field=models.IntegerField(default=0, verbose_name='当期純利益（千円）'),
        ),
        migrations.AddField(
            model_name='fiscalsummary_year',
            name='number_of_employees_EOY',
            field=models.IntegerField(default=0, verbose_name='期末従業員数'),
        ),
        migrations.AddField(
            model_name='fiscalsummary_year',
            name='operating_profit',
            field=models.IntegerField(default=0, verbose_name='営業利益（千円）'),
        ),
        migrations.AddField(
            model_name='fiscalsummary_year',
            name='ordinary_profit',
            field=models.IntegerField(default=0, verbose_name='経常利益（千円）'),
        ),
        migrations.AddField(
            model_name='fiscalsummary_year',
            name='other_current_assets',
            field=models.IntegerField(default=0, verbose_name='その他の流動資産（千円）'),
        ),
        migrations.AddField(
            model_name='fiscalsummary_year',
            name='other_current_liabilities',
            field=models.IntegerField(default=0, verbose_name='その他の流動負債（千円）'),
        ),
        migrations.AddField(
            model_name='fiscalsummary_year',
            name='other_long_term_liabilities',
            field=models.IntegerField(default=0, verbose_name='その他の固定負債（千円）'),
        ),
        migrations.AddField(
            model_name='fiscalsummary_year',
            name='other_tangible_fixed_assets',
            field=models.IntegerField(default=0, verbose_name='その他の有形固定資産（千円）'),
        ),
        migrations.AddField(
            model_name='fiscalsummary_year',
            name='payroll_expense',
            field=models.IntegerField(default=0, verbose_name='給与・雑給（千円）'),
        ),
        migrations.AddField(
            model_name='fiscalsummary_year',
            name='sales',
            field=models.IntegerField(default=0, verbose_name='売上高（千円）'),
        ),
        migrations.AddField(
            model_name='fiscalsummary_year',
            name='total_long_term_liabilities',
            field=models.IntegerField(default=0, verbose_name='固定負債合計（千円）'),
        ),
        migrations.AddField(
            model_name='fiscalsummary_year',
            name='vehicles',
            field=models.IntegerField(default=0, verbose_name='車両運搬具（千円）'),
        ),
        migrations.AddField(
            model_name='meetingminutes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetingminutes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='fiscalsummary_year',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='年度'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'このユーザー名は既に使用されています。'}, help_text='20文字以下のユーザー名を入力してください。', max_length=20, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='ユーザー名'),
        ),
        migrations.CreateModel(
            name='StackHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('share_quantity', models.IntegerField(default=0, verbose_name='株式数')),
                ('share_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreai.company')),
            ],
        ),
    ]
