# Generated by Django 5.0.4 on 2024-10-01 07:49

import django.db.models.deletion
import ulid.api.api
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreai', '0025_alter_user_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stackholder',
            name='company',
        ),
        migrations.AddField(
            model_name='stackholder',
            name='fiscal_summary_year',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='stackholders', to='scoreai.fiscalsummary_year'),
            preserve_default=False,
        ),
    ]
