# Generated by Django 5.0.4 on 2024-10-01 07:51

import ulid.api.api
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreai', '0026_remove_stackholder_company_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StackHolder',
            new_name='StakeHolder',
        ),

    ]
