# Generated by Django 5.0.4 on 2024-10-01 08:42

import ulid.api.api
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreai', '0027_rename_stackholder_stakeholder_alter_company_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stakeholder_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
