# Generated by Django 5.0.4 on 2024-10-01 08:49

import ulid.api.api
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreai', '0028_stakeholder_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakeholder_name',
            name='is_board_member',
            field=models.BooleanField(default=True, verbose_name='取締役'),
        ),
        migrations.AddField(
            model_name='stakeholder_name',
            name='is_employee',
            field=models.BooleanField(default=False, verbose_name='従業員'),
        ),
        migrations.AddField(
            model_name='stakeholder_name',
            name='is_related_person',
            field=models.BooleanField(default=True, verbose_name='代表者の家族'),
        ),
        migrations.AddField(
            model_name='stakeholder_name',
            name='is_representative',
            field=models.BooleanField(default=True, verbose_name='代表取締役'),
        ),
        migrations.AddField(
            model_name='stakeholder_name',
            name='memo',
            field=models.TextField(blank=True, verbose_name='備考'),
        ),
    ]
