# Generated by Django 5.0.4 on 2024-10-01 09:10

import django.db.models.deletion
import ulid.api.api
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreai', '0031_stakeholder_name_company_alter_company_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stakeholder',
            name='fiscal_summary_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stakeholders', to='scoreai.fiscalsummary_year'),
        ),
    ]
