# Generated by Django 5.0.4 on 2024-10-01 10:37

import django.core.validators
import ulid.api.api
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreai', '0034_remove_stakeholder_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalsummary_year',
            name='accumulated_depreciation',
            field=models.IntegerField(default=0, help_text='有形固定資産の取得原価から減価償却累計額を引いた額。直接法の場合はゼロ。', validators=[django.core.validators.MaxValueValidator(0)], verbose_name='有形固定資産の減価償却累計額（千円）'),
        ),
    ]
