# Generated by Django 5.0.4 on 2024-10-01 23:23

import ulid.api.api
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreai', '0036_fiscalsummary_year_other_intangible_assets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalsummary_year',
            name='investment_other_assets',
            field=models.IntegerField(default=0, verbose_name='投資その他の資産（千円）'),
        ),
        migrations.AddField(
            model_name='fiscalsummary_year',
            name='long_term_loans_receivable',
            field=models.IntegerField(default=0, verbose_name='長期貸付金（千円）'),
        ),
        migrations.AddField(
            model_name='fiscalsummary_year',
            name='short_term_loans_receivable',
            field=models.IntegerField(default=0, verbose_name='短期貸付金（千円）'),
        ),
    ]
