# Generated by Django 5.0.4 on 2024-10-02 03:45

import ulid.api.api
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreai', '0037_fiscalsummary_year_investment_other_assets_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fiscalsummary_year',
            old_name='extraordinary_profit',
            new_name='extraordinary_income',
        ),
        migrations.AddField(
            model_name='fiscalsummary_year',
            name='capital_surplus',
            field=models.IntegerField(default=0, verbose_name='資本剰余金（千円）'),
        ),
        migrations.AddField(
            model_name='fiscalsummary_year',
            name='interest_expense',
            field=models.IntegerField(default=0, verbose_name='支払い利息（千円）'),
        ),
        migrations.AddField(
            model_name='fiscalsummary_year',
            name='new_shares_reserve',
            field=models.IntegerField(default=0, verbose_name='新株予約権（千円）'),
        ),
        migrations.AddField(
            model_name='fiscalsummary_year',
            name='other_income',
            field=models.IntegerField(default=0, verbose_name='雑収入（千円）'),
        ),
        migrations.AddField(
            model_name='fiscalsummary_year',
            name='other_loss',
            field=models.IntegerField(default=0, verbose_name='雑損失（千円）'),
        ),
        migrations.AddField(
            model_name='fiscalsummary_year',
            name='total_stakeholder_equity',
            field=models.IntegerField(default=0, verbose_name='株主資本合計（千円）'),
        ),
        migrations.AddField(
            model_name='fiscalsummary_year',
            name='valuation_and_translation_adjustment',
            field=models.IntegerField(default=0, verbose_name='評価・換算差額（千円）'),
        ),
        migrations.AlterField(
            model_name='fiscalsummary_year',
            name='retained_earnings',
            field=models.IntegerField(default=0, verbose_name='利益剰余金（千円）'),
        ),
    ]
