# Generated by Django 5.0.4 on 2024-10-02 03:48

import ulid.api.api
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreai', '0038_rename_extraordinary_profit_fiscalsummary_year_extraordinary_income_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiscalsummary_year',
            name='capital_reserve',
        ),
        migrations.AlterField(
            model_name='fiscalsummary_year',
            name='interest_expense',
            field=models.IntegerField(default=0, verbose_name='支払利息（千円）'),
        ),
    ]
