# Generated by Django 5.0.4 on 2024-10-02 06:44

import django.core.validators
import django.db.models.deletion
import ulid.api.api
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreai', '0039_remove_fiscalsummary_year_capital_reserve_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='written_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fiscalsummary_year',
            name='buildings',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='建物及び附属設備（千円）'),
        ),
        migrations.AlterField(
            model_name='fiscalsummary_year',
            name='capital_stock',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='資本金（千円）'),
        ),
        migrations.AlterField(
            model_name='fiscalsummary_year',
            name='capital_surplus',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='資本剰余金（千円）'),
        ),
        migrations.AlterField(
            model_name='fiscalsummary_year',
            name='issued_shares_EOY',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='期末発行済み株式数（株）'),
        ),
        migrations.AlterField(
            model_name='fiscalsummary_year',
            name='land',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='土地（千円）'),
        ),
        migrations.AlterField(
            model_name='fiscalsummary_year',
            name='machinery_equipment',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='機械及び装置（千円）'),
        ),
        migrations.AlterField(
            model_name='fiscalsummary_year',
            name='number_of_employees_EOY',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='期末従業員数'),
        ),
        migrations.AlterField(
            model_name='fiscalsummary_year',
            name='tax_loss_carryforward',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='繰越欠損金（千円）'),
        ),
        migrations.AlterField(
            model_name='fiscalsummary_year',
            name='total_assets',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='資産の部合計（千円）'),
        ),
        migrations.AlterField(
            model_name='fiscalsummary_year',
            name='total_liabilities',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='負債の部合計（千円）'),
        ),
        migrations.AlterField(
            model_name='fiscalsummary_year',
            name='vehicles',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='車両運搬具（千円）'),
        ),
    ]
