# Generated by Django 5.0.4 on 2024-10-02 06:56

import ulid.api.api
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreai', '0040_blog_written_by_alter_company_id_alter_debt_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiscalsummary_year',
            name='salaries_and_other_personnel_expenses',
        ),
    ]
