# Generated by Django 5.0.4 on 2024-10-04 08:34

import django.db.models.deletion
import ulid.api.api
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreai', '0041_remove_fiscalsummary_year_salaries_and_other_personnel_expenses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalsummary_year',
            name='is_draft',
            field=models.BooleanField(default=False, verbose_name='下書きモード'),
        ),
        migrations.AlterField(
            model_name='fiscalsummary_month',
            name='fiscal_summary_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_summaries', to='scoreai.fiscalsummary_year'),
        ),
        migrations.AlterField(
            model_name='meetingminutes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='meetingminutes',
            name='meeting_date',
            field=models.DateField(verbose_name='ミーティング日'),
        ),
        migrations.AlterField(
            model_name='meetingminutes',
            name='notes',
            field=models.TextField(verbose_name='ミーティングノート'),
        ),
        migrations.AlterField(
            model_name='meetingminutes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日'),
        ),
    ]
