# Generated by Django 5.0.4 on 2024-10-04 23:29

import ulid.api.api
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreai', '0042_fiscalsummary_year_is_draft_alter_company_id_and_more'),
    ]

    operations = [

        migrations.AlterField(
            model_name='stakeholder_name',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
    ]
