# Generated by Django 5.0.4 on 2024-10-09 03:30

import ulid.api.api
from django.db import migrations, models
from datetime import datetime, timedelta, date

class Migration(migrations.Migration):

    dependencies = [
        ('scoreai', '0043_alter_stakeholder_name_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakeholder',
            name='acquisition_date',
            field=models.DateField(default=date.today, verbose_name='取得日'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='acquisition_price',
            field=models.IntegerField(default=0, verbose_name='取得単価'),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='memo',
            field=models.TextField(blank=True, verbose_name='備考'),
        ),
    ]
