# Generated by Django 5.0.4 on 2024-10-09 06:42

import ulid.api.api
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreai', '0044_stakeholder_acquisition_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stakeholder',
            name='share_percentage',
        ),
    ]
