# Generated by Django 5.0.4 on 2024-10-16 10:01

import ulid.api.api
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreai', '0045_remove_stakeholder_share_percentage_alter_company_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='is_rescheduled',
            field=models.BooleanField(default=False, verbose_name='リスケ'),
        ),

    ]
