# Generated by Django 5.0.4 on 2024-10-17 11:55

import django.db.models.deletion
import ulid.api.api
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreai', '0047_industryclassification_alter_company_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='industry_classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='scoreai.industryclassification'),
        ),
    ]
