# Generated by Django 5.0.4 on 2024-10-18 02:39

import django.db.models.deletion
import ulid.api.api
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreai', '0048_company_industry_classification_alter_company_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_size',
            field=models.CharField(choices=[('s', '小規模'), ('m', '中規模'), ('l', '大規模')], default='small', max_length=10, verbose_name='Company Size'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='is_rescheduled',
            field=models.BooleanField(default=False, help_text='リスケした場合はチェックし、リスケ日とリスケ時点の残高を入力してください。', verbose_name='リスケ'),
        ),
        migrations.CreateModel(
            name='IndustrySubClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='業界小分類名')),
                ('code', models.CharField(max_length=7, unique=True, verbose_name='小分類コード')),
                ('memo', models.TextField(blank=True, verbose_name='備考')),
                ('industry_classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreai.industryclassification')),
            ],
        ),
    ]
