# Generated by Django 5.0.4 on 2024-10-18 03:47

import django.db.models.deletion
import ulid.api.api
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreai', '0049_company_company_size_alter_company_id_alter_debt_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='industry_subclassification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scoreai.industrysubclassification'),
        ),
        migrations.AlterField(
            model_name='company',
            name='industry_classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scoreai.industryclassification'),
        ),
    ]
