# Generated by Django 5.0.4 on 2024-10-18 04:05

import django.db.models.deletion
import ulid.api.api
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreai', '0050_company_industry_subclassification_alter_company_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='industry_classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scoreai.industryclassification'),
        ),
        migrations.AlterField(
            model_name='company',
            name='industry_subclassification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scoreai.industrysubclassification'),
        ),
    ]
