# Generated by Django 5.0.4 on 2024-10-18 04:31

import django.core.validators
import django.db.models.deletion
import ulid.api.api
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreai', '0051_alter_company_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_size',
            field=models.CharField(choices=[('s', '小規模'), ('m', '中規模'), ('l', '大規模')], default='s', max_length=10, verbose_name='Company Size'),
        ),
        migrations.CreateModel(
            name='IndustryBenchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='年度')),
                ('company_size', models.CharField(choices=[('s', '小規模'), ('m', '中規模'), ('l', '大規模')], default='s', max_length=10, verbose_name='Company Size')),
                ('indicator_name', models.CharField(max_length=255, verbose_name='指標名')),
                ('median', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='中央値')),
                ('standard_deviation', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='標準偏差')),
                ('range_iv', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='iv')),
                ('range_iii', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='iii')),
                ('range_ii', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='ii')),
                ('range_i', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='i')),
                ('memo', models.TextField(blank=True, verbose_name='備考')),
                ('industry_classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreai.industryclassification')),
                ('industry_subclassification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreai.industrysubclassification')),
            ],
            options={
                'verbose_name': '業界別経営指標',
                'verbose_name_plural': '業界別経営指標',
                'unique_together': {('year', 'industry_classification', 'industry_subclassification', 'company_size')},
            },
        ),
    ]
