# Generated by Django 5.0.4 on 2024-10-18 04:56

import ulid.api.api
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreai', '0052_alter_company_company_size_alter_company_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='指標名')),
                ('memo', models.TextField(blank=True, verbose_name='備考')),
            ],
        ),

    ]
