# Generated by Django 5.0.4 on 2024-10-18 05:00

import django.db.models.deletion
import ulid.api.api
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreai', '0053_industryindicator_alter_company_id_alter_debt_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industrybenchmark',
            name='indicator_name',
        ),
        migrations.AddField(
            model_name='industrybenchmark',
            name='indicator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scoreai.industryindicator'),
            preserve_default=False,
        ),
    ]
