# Generated by Django 5.0.4 on 2024-10-18 06:37

import ulid.api.api
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreai', '0054_remove_industrybenchmark_indicator_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='industrybenchmark',
            unique_together={('year', 'industry_classification', 'industry_subclassification', 'company_size', 'indicator')},
        ),
    ]
