# Generated by Django 5.0.4 on 2024-10-18 08:38

import ulid.api.api
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreai', '0055_AlterUniqueTogether'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='用語名')),
                ('description1', models.TextField(blank=True, verbose_name='説明1')),
                ('description2', models.TextField(blank=True, verbose_name='説明2')),
                ('description3', models.TextField(blank=True, verbose_name='計算式')),
            ],
        ),

    ]
