# Generated by Django 5.0.4 on 2024-10-21 12:09

import django.core.validators
import ulid.api.api
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreai', '0056_technicalterm_alter_company_id_alter_debt_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalsummary_year',
            name='score_EBITDA_interest_bearing_debt_ratio',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='EBITDA有利子負債倍率'),
        ),
        migrations.AddField(
            model_name='fiscalsummary_year',
            name='score_equity_ratio',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='自己資本比率'),
        ),
        migrations.AddField(
            model_name='fiscalsummary_year',
            name='score_labor_productivity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='労働生産性'),
        ),
        migrations.AddField(
            model_name='fiscalsummary_year',
            name='score_operating_profit_margin',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='営業利益率'),
        ),
        migrations.AddField(
            model_name='fiscalsummary_year',
            name='score_operating_working_capital_turnover_period',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='営業運転資本回転期間'),
        ),
        migrations.AddField(
            model_name='fiscalsummary_year',
            name='score_sales_growth_rate',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='売上高増加率'),
        ),
        migrations.AlterField(
            model_name='technicalterm',
            name='description1',
            field=models.TextField(blank=True, verbose_name='説明'),
        ),
        migrations.AlterField(
            model_name='technicalterm',
            name='description2',
            field=models.TextField(blank=True, verbose_name='目安'),
        ),
    ]
