# Generated by Django 5.0.4 on 2024-10-22 09:19

import django.db.models.deletion
import ulid.api.api
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreai', '0059_industryindicator_label_alter_company_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='株式イベント名')),
                ('event_date', models.DateField(verbose_name='日付')),
                ('event_type', models.CharField(max_length=255, verbose_name='種別')),
                ('memo', models.TextField(blank=True, verbose_name='備考')),
                ('fiscal_summary_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_events', to='scoreai.fiscalsummary_year')),
            ],
        ),
    ]
