# Generated by Django 5.0.4 on 2024-10-22 09:21

import django.db.models.deletion
import ulid.api.api
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreai', '0060_alter_company_id_alter_debt_id_alter_firm_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockEventDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_quantity', models.IntegerField(default=0, verbose_name='株式数')),
                ('share_type', models.CharField(max_length=255, verbose_name='株式種類')),
                ('acquisition_price', models.IntegerField(default=0, verbose_name='取得単価')),
                ('memo', models.TextField(blank=True, verbose_name='備考')),
                ('stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scoreai.stakeholder_name')),
                ('stock_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='scoreai.stockevent')),
            ],
        ),
    ]
