# Generated by Django 5.1.2 on 2024-11-24 08:59

import ulid.api.api
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreai', '0062_rename_stockeventdetail_stockeventline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('category', models.CharField(choices=[('login', 'ログインについて'), ('others', 'その他')], default='others', max_length=50)),
                ('content', models.TextField(verbose_name='内容')),
            ],
        ),
        migrations.AlterField(
            model_name='debt',
            name='interest_rate',
            field=models.DecimalField(decimal_places=4, help_text='単位：%', max_digits=6, verbose_name='利息'),
        ),
    ]
