# Generated by Django 5.1.2 on 2024-11-24 11:49

import ulid.api.api
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreai', '0063_help_alter_company_id_alter_debt_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debt',
            name='payment_terms',
        ),
    ]
