# Generated by Django 5.1.2 on 2024-11-26 11:37

import ulid.api.api
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreai', '0064_remove_debt_payment_terms_alter_company_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='document_url',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='クラウドストレージへのリンク'),
        ),
        migrations.AddField(
            model_name='fiscalsummary_year',
            name='document_url',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='クラウドストレージへのリンク'),
        ),
    ]
