# Generated by Django 5.1.2 on 2024-12-04 21:04

import django.core.validators
import ulid.api.api
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreai', '0065_debt_document_url_fiscalsummary_year_document_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalsummary_year',
            name='accounts_payable',
            field=models.IntegerField(default=0, verbose_name='仕入債務合計（千円）'),
        ),
        migrations.AlterField(
            model_name='fiscalsummary_year',
            name='accounts_receivable',
            field=models.IntegerField(default=0, verbose_name='売上債権合計（千円）'),
        ),
        migrations.AlterField(
            model_name='fiscalsummary_year',
            name='capital_stock',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='資本金合計（千円）'),
        ),
        migrations.AlterField(
            model_name='fiscalsummary_year',
            name='capital_surplus',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='資本剰余金合計（千円）'),
        ),
        migrations.AlterField(
            model_name='fiscalsummary_year',
            name='cash_and_deposits',
            field=models.IntegerField(default=0, verbose_name='現金及び預金合計（千円）'),
        ),
        migrations.AlterField(
            model_name='fiscalsummary_year',
            name='deferred_assets',
            field=models.IntegerField(default=0, verbose_name='繰延資産合計（千円）'),
        ),
        migrations.AlterField(
            model_name='fiscalsummary_year',
            name='extraordinary_income',
            field=models.IntegerField(default=0, verbose_name='特別利益合計（千円）'),
        ),
        migrations.AlterField(
            model_name='fiscalsummary_year',
            name='extraordinary_loss',
            field=models.IntegerField(default=0, verbose_name='特別損失合計（千円）'),
        ),
        migrations.AlterField(
            model_name='fiscalsummary_year',
            name='inventory',
            field=models.IntegerField(default=0, verbose_name='棚卸資産合計（千円）'),
        ),
        migrations.AlterField(
            model_name='fiscalsummary_year',
            name='new_shares_reserve',
            field=models.IntegerField(default=0, verbose_name='新株予約権合計（千円）'),
        ),
        migrations.AlterField(
            model_name='fiscalsummary_year',
            name='other_income',
            field=models.IntegerField(default=0, verbose_name='営業外収益合計（千円）'),
        ),
        migrations.AlterField(
            model_name='fiscalsummary_year',
            name='other_loss',
            field=models.IntegerField(default=0, verbose_name='営業外費用合計（千円）'),
        ),
        migrations.AlterField(
            model_name='fiscalsummary_year',
            name='retained_earnings',
            field=models.IntegerField(default=0, verbose_name='利益剰余金合計（千円）'),
        ),
        migrations.AlterField(
            model_name='fiscalsummary_year',
            name='valuation_and_translation_adjustment',
            field=models.IntegerField(default=0, verbose_name='評価・換算差額合計（千円）'),
        ),
    ]
