# Generated by Django 5.1.2 on 2024-12-08 10:16

import ulid.api.api
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreai', '0067_technicalterm_term_category_alter_company_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercompany',
            name='as_consultant',
            field=models.BooleanField(default=False),
        ),
    ]
