# Generated by Django 5.1.2 on 2024-12-20 00:21

import ulid.api.api
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreai', '0068_usercompany_as_consultant_alter_company_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='document_url2',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='金銭消費貸借契約書へのリンク'),
        ),
        migrations.AddField(
            model_name='debt',
            name='document_url3',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='保証協会資料・担保契約書などへのリンク'),
        ),
        migrations.AddField(
            model_name='debt',
            name='document_url4',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='その他資料へのリンク'),
        ),
        migrations.AddField(
            model_name='debt',
            name='document_url_c1',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='コンサル用資料リンク１'),
        ),
        migrations.AddField(
            model_name='debt',
            name='document_url_c2',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='コンサル用資料リンク２'),
        ),
        migrations.AddField(
            model_name='debt',
            name='document_url_c3',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='コンサル用資料リンク３'),
        ),
        migrations.AddField(
            model_name='fiscalsummary_month',
            name='is_budget',
            field=models.BooleanField(default=False, verbose_name='予算'),
        ),
        migrations.AddField(
            model_name='fiscalsummary_year',
            name='is_budget',
            field=models.BooleanField(default=False, verbose_name='予算'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='document_url',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='返済予定表へのリンク'),
        ),
    ]
