# Generated by Django 5.1.2 on 2024-12-20 08:15

import django.core.validators
import ulid.api.api
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreai', '0069_debt_document_url2_debt_document_url3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='monthly_repayment',
            field=models.IntegerField(help_text='単位：円', validators=[django.core.validators.MinValueValidator(0)], verbose_name='月返済額'),
        ),
    ]
