# Generated by Django 5.1.2 on 2024-12-20 08:27

import ulid.api.api
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreai', '0070_alter_company_id_alter_debt_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='monthly_repayment',
            field=models.IntegerField(help_text='単位：円', verbose_name='月返済額'),
        ),
    ]
