# Generated by Django 5.1.2 on 2025-12-26 04:48

import django.db.models.deletion
import ulid.api.api
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreai', '0071_alter_company_id_alter_debt_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConsultationType',
            fields=[
                ('id', models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='相談タイプ名')),
                ('icon', models.CharField(max_length=20, verbose_name='アイコン')),
                ('description', models.TextField(verbose_name='説明')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('order', models.IntegerField(default=0, verbose_name='表示順序')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='カラー')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI相談タイプ',
                'verbose_name_plural': 'AI相談タイプ',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='debt',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='firm',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='firmcompany',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fiscalsummary_year',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stakeholder_name',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usercompany',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userfirm',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='AIConsultationScript',
            fields=[
                ('id', models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='スクリプト名')),
                ('system_instruction', models.TextField(verbose_name='システムプロンプト')),
                ('default_prompt_template', models.TextField(verbose_name='プロンプトテンプレート')),
                ('is_default', models.BooleanField(default=True, verbose_name='デフォルト')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('consultation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_scripts', to='scoreai.aiconsultationtype', verbose_name='相談タイプ')),
            ],
            options={
                'verbose_name': 'AI相談スクリプト（システム）',
                'verbose_name_plural': 'AI相談スクリプト（システム）',
                'unique_together': {('consultation_type', 'is_default')},
            },
        ),
        migrations.CreateModel(
            name='UserAIConsultationScript',
            fields=[
                ('id', models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='スクリプト名')),
                ('system_instruction', models.TextField(verbose_name='システムプロンプト')),
                ('prompt_template', models.TextField(verbose_name='プロンプトテンプレート')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('is_default', models.BooleanField(default=False, verbose_name='デフォルト')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_scripts', to='scoreai.aiconsultationtype', verbose_name='相談タイプ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_scripts', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'AI相談スクリプト（ユーザー）',
                'verbose_name_plural': 'AI相談スクリプト（ユーザー）',
                'unique_together': {('user', 'consultation_type', 'is_default')},
            },
        ),
        migrations.CreateModel(
            name='AIConsultationHistory',
            fields=[
                ('id', models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('user_message', models.TextField(verbose_name='ユーザーの質問')),
                ('ai_response', models.TextField(verbose_name='AIの応答')),
                ('data_snapshot', models.JSONField(default=dict, verbose_name='データスナップショット')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_histories', to='scoreai.company', verbose_name='会社')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_histories', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
                ('script_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scoreai.aiconsultationscript', verbose_name='使用したスクリプト（システム）')),
                ('consultation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreai.aiconsultationtype', verbose_name='相談タイプ')),
                ('user_script_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scoreai.useraiconsultationscript', verbose_name='使用したスクリプト（ユーザー）')),
            ],
            options={
                'verbose_name': 'AI相談履歴',
                'verbose_name_plural': 'AI相談履歴',
                'ordering': ['-created_at'],
            },
        ),
    ]
