# Generated by Django 5.1.2 on 2025-12-27 23:03

import django.db.models.deletion
import ulid.api.api
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreai', '0072_aiconsultationtype_alter_company_id_alter_debt_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiconsultationhistory',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='aiconsultationscript',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='aiconsultationtype',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='debt',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='firm',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='firmcompany',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fiscalsummary_year',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stakeholder_name',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='useraiconsultationscript',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usercompany',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userfirm',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='CloudStorageSetting',
            fields=[
                ('id', models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('storage_type', models.CharField(blank=True, choices=[('google_drive', 'Google Drive'), ('box', 'Box'), ('dropbox', 'Dropbox'), ('onedrive', 'OneDrive')], max_length=20, null=True, verbose_name='ストレージタイプ')),
                ('access_token', models.TextField(blank=True, help_text='OAuth2アクセストークン（暗号化推奨）', verbose_name='アクセストークン')),
                ('refresh_token', models.TextField(blank=True, help_text='OAuth2リフレッシュトークン（暗号化推奨）', verbose_name='リフレッシュトークン')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='トークン有効期限')),
                ('root_folder_id', models.CharField(blank=True, help_text='ストレージ内のルートフォルダID', max_length=255, verbose_name='ルートフォルダID')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_storage_setting', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'クラウドストレージ設定',
                'verbose_name_plural': 'クラウドストレージ設定',
            },
        ),
        migrations.CreateModel(
            name='DocumentFolder',
            fields=[
                ('id', models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('folder_type', models.CharField(choices=[('financial_statement', '決算書'), ('trial_balance', '試算表'), ('loan_contract', '金銭消費貸借契約書'), ('contract', '契約書')], max_length=30, verbose_name='フォルダタイプ')),
                ('subfolder_type', models.CharField(blank=True, choices=[('balance_sheet', '貸借対照表'), ('profit_loss', '損益計算書'), ('monthly_pl', '月次推移損益計算書'), ('department_pl', '部門別損益計算書'), ('lease', 'リース契約書'), ('sales', '商品売買契約'), ('rental', '賃貸借契約')], max_length=30, verbose_name='サブフォルダタイプ')),
                ('name', models.CharField(max_length=100, verbose_name='フォルダ名')),
                ('order', models.IntegerField(default=0, verbose_name='表示順')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ドキュメントフォルダ',
                'verbose_name_plural': 'ドキュメントフォルダ',
                'ordering': ['folder_type', 'order', 'subfolder_type'],
                'unique_together': {('folder_type', 'subfolder_type')},
            },
        ),
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('financial_statement', '決算書'), ('trial_balance', '試算表'), ('loan_contract', '金銭消費貸借契約書'), ('contract', '契約書'), ('other', 'その他')], max_length=30, verbose_name='ドキュメントタイプ')),
                ('subfolder_type', models.CharField(blank=True, max_length=30, verbose_name='サブフォルダタイプ')),
                ('original_filename', models.CharField(max_length=255, verbose_name='元のファイル名')),
                ('stored_filename', models.CharField(help_text='システムが自動生成したファイル名', max_length=255, verbose_name='保存ファイル名')),
                ('storage_type', models.CharField(choices=[('google_drive', 'Google Drive'), ('box', 'Box'), ('dropbox', 'Dropbox'), ('onedrive', 'OneDrive')], max_length=20, verbose_name='ストレージタイプ')),
                ('file_id', models.CharField(help_text='ストレージ内のファイルID', max_length=255, verbose_name='ファイルID')),
                ('folder_id', models.CharField(help_text='ストレージ内のフォルダID', max_length=255, verbose_name='フォルダID')),
                ('file_url', models.URLField(blank=True, max_length=500, verbose_name='ファイルURL')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='ファイルサイズ（バイト）')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='MIMEタイプ')),
                ('is_ocr_processed', models.BooleanField(default=False, verbose_name='OCR処理済み')),
                ('ocr_processed_at', models.DateTimeField(blank=True, null=True, verbose_name='OCR処理日時')),
                ('is_data_saved', models.BooleanField(default=False, verbose_name='データ保存済み')),
                ('saved_to_model', models.CharField(blank=True, help_text='例: FiscalSummary_Year, Debt', max_length=50, verbose_name='保存先モデル')),
                ('saved_record_id', models.CharField(blank=True, max_length=26, verbose_name='保存レコードID')),
                ('metadata', models.JSONField(blank=True, help_text='追加情報（年度、金融機関名など）', null=True, verbose_name='メタデータ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to='scoreai.company', verbose_name='会社')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'アップロードドキュメント',
                'verbose_name_plural': 'アップロードドキュメント',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'company', 'document_type'], name='scoreai_upl_user_id_3afaa7_idx'), models.Index(fields=['is_ocr_processed'], name='scoreai_upl_is_ocr__f02519_idx'), models.Index(fields=['is_data_saved'], name='scoreai_upl_is_data_e44532_idx')],
            },
        ),
    ]
