# Generated by Django 5.1.2 on 2025-12-28

import django.core.validators
import django.utils.timezone
import ulid.api.api
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoreai', '0075_blogcategory_alter_blog_options_blog_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmPlan',
            fields=[
                ('id', models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('plan_type', models.CharField(choices=[('free', 'Freeプラン（無料・試用）'), ('starter', 'Starterプラン'), ('professional', 'Professionalプラン'), ('enterprise', 'Enterpriseプラン')], max_length=20, unique=True, verbose_name='プランタイプ')),
                ('name', models.CharField(max_length=255, verbose_name='プラン名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0, help_text='0の場合は無制限', max_digits=10, verbose_name='月額料金')),
                ('yearly_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='年額料金')),
                ('yearly_discount_months', models.IntegerField(default=2, verbose_name='年払い割引（無料月数）')),
                ('max_companies', models.IntegerField(default=1, help_text='0の場合は無制限', verbose_name='最大Company数')),
                ('max_ai_consultations_per_month', models.IntegerField(default=10, help_text='0の場合は無制限', verbose_name='月間AI相談回数上限')),
                ('max_ocr_per_month', models.IntegerField(default=5, help_text='0の場合は無制限', verbose_name='月間OCR読み込み回数上限')),
                ('cloud_storage_google_drive', models.BooleanField(default=False, verbose_name='Google Drive連携')),
                ('cloud_storage_box', models.BooleanField(default=False, verbose_name='Box連携')),
                ('cloud_storage_dropbox', models.BooleanField(default=False, verbose_name='Dropbox連携')),
                ('cloud_storage_onedrive', models.BooleanField(default=False, verbose_name='OneDrive連携')),
                ('report_basic', models.BooleanField(default=True, verbose_name='基本レポート')),
                ('report_advanced', models.BooleanField(default=False, verbose_name='高度なレポート（PDF/Excel）')),
                ('report_custom', models.BooleanField(default=False, verbose_name='カスタムレポート')),
                ('marketing_support', models.BooleanField(default=False, verbose_name='マーケティング支援')),
                ('marketing_support_seminar', models.IntegerField(default=0, verbose_name='セミナー共催回数/年')),
                ('marketing_support_offline', models.IntegerField(default=0, verbose_name='オフ会実施支援回数/年')),
                ('marketing_support_newsletter', models.BooleanField(default=False, verbose_name='メルマガ配信支援')),
                ('api_integration', models.BooleanField(default=False, verbose_name='API連携')),
                ('priority_support', models.BooleanField(default=False, verbose_name='優先サポート')),
                ('profile_page_enhanced', models.BooleanField(default=False, verbose_name='プロフィールページ強化')),
                ('stripe_price_id_monthly', models.CharField(blank=True, max_length=255, verbose_name='Stripe月額価格ID')),
                ('stripe_price_id_yearly', models.CharField(blank=True, max_length=255, verbose_name='Stripe年額価格ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('order', models.IntegerField(default=0, verbose_name='表示順')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Firmプラン',
                'verbose_name_plural': 'Firmプラン',
                'ordering': ['order', 'plan_type'],
            },
        ),
        migrations.CreateModel(
            name='FirmSubscription',
            fields=[
                ('id', models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('trial', '試用期間中'), ('active', '有効'), ('past_due', '支払い遅延'), ('canceled', 'キャンセル済み'), ('unpaid', '未払い'), ('incomplete', '未完了'), ('incomplete_expired', '未完了（期限切れ）')], default='trial', max_length=20, verbose_name='ステータス')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='開始日時')),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True, verbose_name='試用期間終了日時')),
                ('current_period_start', models.DateTimeField(blank=True, null=True, verbose_name='現在の請求期間開始日時')),
                ('current_period_end', models.DateTimeField(blank=True, null=True, verbose_name='現在の請求期間終了日時')),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name='キャンセル日時')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='終了日時')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, verbose_name='Stripe顧客ID')),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, verbose_name='StripeサブスクリプションID')),
                ('stripe_price_id', models.CharField(blank=True, max_length=255, verbose_name='Stripe価格ID')),
                ('stripe_payment_method_id', models.CharField(blank=True, max_length=255, verbose_name='Stripe支払い方法ID')),
                ('additional_companies', models.IntegerField(default=0, help_text='Enterpriseプランの場合、10社ごとの追加分', verbose_name='追加Company数')),
                ('billing_cycle', models.CharField(choices=[('monthly', '月払い'), ('yearly', '年払い')], default='monthly', max_length=10, verbose_name='請求サイクル')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('firm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='scoreai.firm', verbose_name='Firm')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='scoreai.firmplan', verbose_name='プラン')),
            ],
            options={
                'verbose_name': 'Firmサブスクリプション',
                'verbose_name_plural': 'Firmサブスクリプション',
            },
        ),
        migrations.CreateModel(
            name='FirmUsageTracking',
            fields=[
                ('id', models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('year', models.IntegerField(verbose_name='年')),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='月')),
                ('ai_consultation_count', models.IntegerField(default=0, verbose_name='AI相談回数')),
                ('ocr_count', models.IntegerField(default=0, verbose_name='OCR読み込み回数')),
                ('is_reset', models.BooleanField(default=False, verbose_name='リセット済み')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_tracking', to='scoreai.firm', verbose_name='Firm')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_tracking', to='scoreai.firmsubscription', verbose_name='サブスクリプション')),
            ],
            options={
                'verbose_name': 'Firm利用状況',
                'verbose_name_plural': 'Firm利用状況',
                'ordering': ['-year', '-month'],
                'unique_together': {('firm', 'year', 'month')},
            },
        ),
    ]

