# Generated by Django 5.1.2 on 2025-12-31 13:43

import django.db.models.deletion
import ulid.api.api
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreai', '0083_alter_aiconsultationhistory_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiconsultationhistory',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='aiconsultationscript',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='aiconsultationtype',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cloudstoragesetting',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='debt',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='documentfolder',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='firm',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='firmcompany',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='firminvitation',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='firmnotification',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='firmplan',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='firmsubscription',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='firmusagetracking',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fiscalsummary_year',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='meetingminutesaiscript',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stakeholder_name',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='uploadeddocument',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='useraiconsultationscript',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usercompany',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userfirm',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='AIConsultationFAQ',
            fields=[
                ('id', models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=200, verbose_name='質問')),
                ('order', models.IntegerField(default=0, verbose_name='表示順序')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='scoreai.aiconsultationtype', verbose_name='相談タイプ')),
            ],
            options={
                'verbose_name': 'AI相談よくある質問',
                'verbose_name_plural': 'AI相談よくある質問',
                'ordering': ['consultation_type', 'order', 'question'],
            },
        ),
    ]
