# Generated by Django 5.1.2 on 2026-01-01 00:12

import django.db.models.deletion
import django.utils.timezone
import ulid.api.api
from django.conf import settings
from django.db import migrations, models


def migrate_existing_settings(apps, schema_editor):
    """
    既存のCloudStorageSettingレコードにCompanyを設定する
    ユーザーの選択中のCompanyを使用する
    """
    CloudStorageSetting = apps.get_model('scoreai', 'CloudStorageSetting')
    UserCompany = apps.get_model('scoreai', 'UserCompany')
    
    for setting in CloudStorageSetting.objects.all():
        # ユーザーの選択中のCompanyを取得
        user_company = UserCompany.objects.filter(
            user=setting.user,
            is_selected=True,
            active=True
        ).first()
        
        if user_company:
            setting.company = user_company.company
            setting.save()
        else:
            # 選択中のCompanyがない場合、最初のアクティブなCompanyを使用
            user_company = UserCompany.objects.filter(
                user=setting.user,
                active=True
            ).first()
            
            if user_company:
                setting.company = user_company.company
                setting.save()
            else:
                # Companyがない場合は削除（通常は発生しない）
                setting.delete()


def reverse_migrate(apps, schema_editor):
    """
    逆マイグレーション：Company単位の設定をユーザー単位に戻す
    同じユーザーの複数の設定がある場合、最初のアクティブな設定のみを保持
    """
    CloudStorageSetting = apps.get_model('scoreai', 'CloudStorageSetting')
    
    # ユーザーごとに最初のアクティブな設定のみを保持
    processed_users = set()
    for setting in CloudStorageSetting.objects.all().order_by('created_at'):
        if setting.user_id not in processed_users:
            processed_users.add(setting.user_id)
        else:
            # 既に処理済みのユーザーの設定は削除
            setting.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('scoreai', '0089_alter_useraiconsultationscript_unique_together_and_more'),
    ]

    operations = [
        # 1. companyフィールドを追加（null=Trueで一時的に許可）
        migrations.AddField(
            model_name='cloudstoragesetting',
            name='company',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='cloud_storage_settings', to='scoreai.company', verbose_name='Company'),
        ),
        # 2. 既存データの移行
        migrations.RunPython(migrate_existing_settings, reverse_migrate),
        # 3. companyフィールドを必須にする
        migrations.AlterField(
            model_name='cloudstoragesetting',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_storage_settings', to='scoreai.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='aiconsultationfaq',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='aiconsultationhistory',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='aiconsultationscript',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='aiconsultationtype',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cloudstoragesetting',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cloudstoragesetting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_storage_settings', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='companyinvitation',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='companyusagetracking',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='debt',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='documentfolder',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='firm',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='firmcompany',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='firminvitation',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='firmnotification',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='firmplan',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='firmsubscription',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='firmusagetracking',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fiscalsummary_year',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='meetingminutesaiscript',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stakeholder_name',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='uploadeddocument',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='useraiconsultationscript',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usercompany',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userfirm',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='cloudstoragesetting',
            unique_together={('user', 'company')},
        ),
    ]
