# Generated by Django 5.1.2 on 2026-01-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreai', '0099_alter_fiscalsummary_year_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingminutes',
            name='category',
            field=models.CharField(
                choices=[
                    ('meeting', '打ち合わせ'),
                    ('shareholders', '株主総会'),
                    ('board', '取締役会'),
                    ('management', '経営会議/執行役員会'),
                    ('other', 'その他'),
                ],
                default='meeting',
                max_length=20,
                verbose_name='カテゴリ'
            ),
        ),
    ]

