# Generated by Django 5.1.2 on 2026-01-04 02:27

import ulid.api.api
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreai', '0105_aiconsultationhistory_input_tokens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='accounting_system',
            field=models.CharField(blank=True, choices=[('yayoi', '弥生会計'), ('freee', 'freee'), ('money_forward', 'Money Forward'), ('kansanbogyo_v', '勘定奉行Vシリーズ'), ('other', 'その他'), ('none', '未使用')], help_text='使用している会計システム', max_length=50, null=True, verbose_name='会計システム'),
        ),
        migrations.AddField(
            model_name='company',
            name='accounting_system_other',
            field=models.CharField(blank=True, help_text='会計システムが「その他」の場合のシステム名', max_length=100, verbose_name='会計システム（その他）'),
        ),
        migrations.AddField(
            model_name='company',
            name='core_system',
            field=models.CharField(blank=True, help_text='使用している基幹システム名（未使用の場合は空白）', max_length=100, verbose_name='基幹システム'),
        ),
        migrations.AddField(
            model_name='company',
            name='hr_management_system',
            field=models.CharField(blank=True, help_text='使用している人事管理システム名（未使用の場合は空白）', max_length=100, verbose_name='人事管理システム'),
        ),
        migrations.AddField(
            model_name='company',
            name='inventory_management_system',
            field=models.CharField(blank=True, help_text='使用している在庫管理システム名（未使用の場合は空白）', max_length=100, verbose_name='在庫管理システム'),
        ),
        migrations.AddField(
            model_name='company',
            name='other_systems',
            field=models.TextField(blank=True, help_text='その他の使用しているシステム情報（複数ある場合は改行で区切る）', verbose_name='その他システム'),
        ),
        migrations.AddField(
            model_name='company',
            name='payroll_system',
            field=models.CharField(blank=True, help_text='使用している給与計算システム名（未使用の場合は空白）', max_length=100, verbose_name='給与計算システム'),
        ),
        migrations.AddField(
            model_name='company',
            name='production_management_system',
            field=models.CharField(blank=True, help_text='使用している生産管理システム名（未使用の場合は空白）', max_length=100, verbose_name='生産管理システム'),
        ),
        migrations.AddField(
            model_name='company',
            name='purchase_management_system',
            field=models.CharField(blank=True, help_text='使用している購買管理システム名（未使用の場合は空白）', max_length=100, verbose_name='購買管理システム'),
        ),
        migrations.AddField(
            model_name='company',
            name='sales_management_system',
            field=models.CharField(blank=True, help_text='使用している販売管理システム名（未使用の場合は空白）', max_length=100, verbose_name='販売管理システム'),
        ),
        migrations.AlterField(
            model_name='aiconsultationfaq',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='aiconsultationhistory',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='aiconsultationscript',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='aiconsultationtype',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cloudstoragesetting',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='companyinvitation',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='companyusagetracking',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='debt',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='documentfolder',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='firm',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='firmcompany',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='firminvitation',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='firmnotification',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='firmplan',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='firmsubscription',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='firmusagetracking',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fiscalsummary_year',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='manual',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='meetingminutesaiscript',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stakeholder_name',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='uploadeddocument',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='useraiconsultationscript',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usercompany',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userfirm',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
    ]
