# Generated by Django 5.1.2 on 2026-01-10 07:08

import django.db.models.deletion
import ulid.api.api
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreai', '0106_company_accounting_system_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryCategory',
            fields=[
                ('id', models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='業界名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('icon', models.CharField(blank=True, help_text='Font Awesome等のアイコン名', max_length=50, verbose_name='アイコン')),
                ('order', models.IntegerField(default=0, verbose_name='表示順')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '業界カテゴリー',
                'verbose_name_plural': '業界カテゴリー',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='aiconsultationfaq',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='aiconsultationhistory',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='aiconsultationscript',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='aiconsultationtype',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cloudstoragesetting',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='companyinvitation',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='companyusagetracking',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='debt',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='documentfolder',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='firm',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='firmcompany',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='firminvitation',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='firmnotification',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='firmplan',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='firmsubscription',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='firmusagetracking',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fiscalsummary_year',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='manual',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='meetingminutesaiscript',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stakeholder_name',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='uploadeddocument',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='useraiconsultationscript',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usercompany',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userfirm',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='IndustryConsultationType',
            fields=[
                ('id', models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='相談タイプ名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('template_type', models.CharField(choices=[('izakaya_plan', '居酒屋出店計画'), ('cafe_plan', 'カフェ出店計画')], max_length=50, verbose_name='テンプレートタイプ')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('order', models.IntegerField(default=0, verbose_name='表示順')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('industry_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_types', to='scoreai.industrycategory', verbose_name='業界カテゴリー')),
            ],
            options={
                'verbose_name': '業界別相談タイプ',
                'verbose_name_plural': '業界別相談タイプ',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IzakayaPlan',
            fields=[
                ('id', models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('store_concept', models.CharField(blank=True, max_length=200, verbose_name='店のコンセプト')),
                ('number_of_seats', models.IntegerField(default=0, verbose_name='席数')),
                ('opening_hours_start', models.TimeField(blank=True, null=True, verbose_name='営業開始時間')),
                ('opening_hours_end', models.TimeField(blank=True, null=True, verbose_name='営業終了時間')),
                ('target_customer', models.CharField(blank=True, max_length=200, verbose_name='ターゲット顧客')),
                ('average_price_per_customer', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='客単価（円）')),
                ('initial_investment', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='初期投資額（円）')),
                ('monthly_rent', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='月額家賃（円）')),
                ('number_of_staff', models.IntegerField(default=0, verbose_name='社員人数')),
                ('staff_monthly_salary', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='社員月給（円）')),
                ('part_time_hours_per_month', models.IntegerField(default=0, verbose_name='アルバイト時間数/月')),
                ('part_time_hourly_wage', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='アルバイト時給（円）')),
                ('sales_coefficients', models.JSONField(blank=True, default=dict, verbose_name='売上係数')),
                ('monthly_revenue', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='月間売上（円）')),
                ('monthly_cost', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='月間経費（円）')),
                ('monthly_profit', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='月間利益（円）')),
                ('payback_period_months', models.IntegerField(blank=True, null=True, verbose_name='回収期間（月）')),
                ('payback_period_years', models.IntegerField(blank=True, null=True, verbose_name='回収期間（年）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('is_draft', models.BooleanField(default=True, verbose_name='下書き')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='izakaya_plans', to='scoreai.company', verbose_name='会社')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='izakaya_plans', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '居酒屋出店計画',
                'verbose_name_plural': '居酒屋出店計画',
                'ordering': ['-created_at'],
            },
        ),
    ]
