# Generated by Django 5.1.2 on 2026-01-10 12:36

import ulid.api.api
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreai', '0108_alter_aiconsultationfaq_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='izakayaplan',
            name='dinner_cost_rate',
            field=models.DecimalField(decimal_places=2, default=30.0, help_text='0-100の値', max_digits=5, verbose_name='夜の原価率（%）'),
        ),
        migrations.AddField(
            model_name='izakayaplan',
            name='dinner_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='夜の営業終了時間'),
        ),
        migrations.AddField(
            model_name='izakayaplan',
            name='dinner_monthly_coefficients',
            field=models.JSONField(blank=True, default=dict, help_text="{'1': 1.0, '2': 1.1, ...}の形式（1-12月）", verbose_name='夜の月毎指数'),
        ),
        migrations.AddField(
            model_name='izakayaplan',
            name='dinner_operating_days',
            field=models.JSONField(blank=True, default=list, help_text="['monday', 'tuesday', ...]の形式", verbose_name='夜の営業曜日'),
        ),
        migrations.AddField(
            model_name='izakayaplan',
            name='dinner_price_per_customer',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='夜の客単価（円）'),
        ),
        migrations.AddField(
            model_name='izakayaplan',
            name='dinner_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='夜の営業開始時間'),
        ),
        migrations.AddField(
            model_name='izakayaplan',
            name='lunch_cost_rate',
            field=models.DecimalField(decimal_places=2, default=30.0, help_text='0-100の値', max_digits=5, verbose_name='昼の原価率（%）'),
        ),
        migrations.AddField(
            model_name='izakayaplan',
            name='lunch_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='昼の営業終了時間'),
        ),
        migrations.AddField(
            model_name='izakayaplan',
            name='lunch_monthly_coefficients',
            field=models.JSONField(blank=True, default=dict, help_text="{'1': 1.0, '2': 1.1, ...}の形式（1-12月）", verbose_name='昼の月毎指数'),
        ),
        migrations.AddField(
            model_name='izakayaplan',
            name='lunch_operating_days',
            field=models.JSONField(blank=True, default=list, help_text="['monday', 'tuesday', ...]の形式", verbose_name='昼の営業曜日'),
        ),
        migrations.AddField(
            model_name='izakayaplan',
            name='lunch_price_per_customer',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='昼の客単価（円）'),
        ),
        migrations.AddField(
            model_name='izakayaplan',
            name='lunch_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='昼の営業開始時間'),
        ),
        migrations.AddField(
            model_name='izakayaplan',
            name='monthly_advertising',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='広告宣伝費（円/月）'),
        ),
        migrations.AddField(
            model_name='izakayaplan',
            name='monthly_cost_of_goods_sold',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='月間売上原価（円）'),
        ),
        migrations.AddField(
            model_name='izakayaplan',
            name='monthly_fees',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='手数料（円/月）'),
        ),
        migrations.AddField(
            model_name='izakayaplan',
            name='monthly_gross_profit',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='月間粗利益（円）'),
        ),
        migrations.AddField(
            model_name='izakayaplan',
            name='monthly_other_expenses',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='その他販管費（円/月）'),
        ),
        migrations.AddField(
            model_name='izakayaplan',
            name='monthly_supplies',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='消耗品費（円/月）'),
        ),
        migrations.AddField(
            model_name='izakayaplan',
            name='monthly_utilities',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='光熱費（円/月）'),
        ),
        migrations.AlterField(
            model_name='aiconsultationfaq',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='aiconsultationhistory',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='aiconsultationscript',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='aiconsultationtype',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cloudstoragesetting',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='companyinvitation',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='companyusagetracking',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='debt',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='documentfolder',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='firm',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='firmcompany',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='firminvitation',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='firmnotification',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='firmplan',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='firmsubscription',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='firmusagetracking',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fiscalsummary_year',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='industrycategory',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='industryconsultationtype',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='izakayaplan',
            name='average_price_per_customer',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='客単価（円）（旧）'),
        ),
        migrations.AlterField(
            model_name='izakayaplan',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='izakayaplan',
            name='opening_hours_end',
            field=models.TimeField(blank=True, null=True, verbose_name='営業終了時間（旧）'),
        ),
        migrations.AlterField(
            model_name='izakayaplan',
            name='opening_hours_start',
            field=models.TimeField(blank=True, null=True, verbose_name='営業開始時間（旧）'),
        ),
        migrations.AlterField(
            model_name='izakayaplan',
            name='sales_coefficients',
            field=models.JSONField(blank=True, default=dict, verbose_name='売上係数（旧）'),
        ),
        migrations.AlterField(
            model_name='manual',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='meetingminutesaiscript',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stakeholder_name',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='uploadeddocument',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='useraiconsultationscript',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usercompany',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userfirm',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
    ]
