# Generated by Django 5.1.2 on 2026-01-12 22:18

import ulid.api.api
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreai', '0120_usercompany_is_manager_alter_aiconsultationfaq_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debt',
            options={'verbose_name': '借入', 'verbose_name_plural': '借入'},
        ),
        migrations.AlterField(
            model_name='aiconsultationfaq',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='aiconsultationhistory',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='aiconsultationscript',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='aiconsultationtype',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cloudstoragesetting',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='companyinvitation',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='companyusagetracking',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='debt',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='documentfolder',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='firm',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='firmcompany',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='firminvitation',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='firmnotification',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='firmplan',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='firmsubscription',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='firmusagetracking',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fiscalsummary_year',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='izakayaplan',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='manual',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='meetingminutesaiscript',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stakeholder_name',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='uploadeddocument',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='useraiconsultationscript',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usercompany',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userfirm',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='aiconsultationhistory',
            index=models.Index(fields=['user', 'company', '-created_at'], name='scoreai_aic_user_id_1da866_idx'),
        ),
        migrations.AddIndex(
            model_name='aiconsultationhistory',
            index=models.Index(fields=['company', 'consultation_type', '-created_at'], name='scoreai_aic_company_d40c2c_idx'),
        ),
        migrations.AddIndex(
            model_name='debt',
            index=models.Index(fields=['company', 'is_nodisplay', 'is_rescheduled'], name='scoreai_deb_company_64d5d4_idx'),
        ),
        migrations.AddIndex(
            model_name='debt',
            index=models.Index(fields=['company', 'financial_institution'], name='scoreai_deb_company_3fd07e_idx'),
        ),
        migrations.AddIndex(
            model_name='debt',
            index=models.Index(fields=['company', 'start_date'], name='scoreai_deb_company_03c765_idx'),
        ),
        migrations.AddIndex(
            model_name='debt',
            index=models.Index(fields=['company', 'debt_type'], name='scoreai_deb_company_51673b_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalsummary_month',
            index=models.Index(fields=['fiscal_summary_year', 'period', 'is_budget'], name='scoreai_fis_fiscal__638eeb_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalsummary_month',
            index=models.Index(fields=['fiscal_summary_year', 'period'], name='scoreai_fis_fiscal__8a4d5b_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalsummary_year',
            index=models.Index(fields=['company', 'year', 'is_budget', 'is_draft'], name='scoreai_fis_company_61b543_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalsummary_year',
            index=models.Index(fields=['company', 'is_budget', 'is_draft', '-year'], name='scoreai_fis_company_baa2d9_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalsummary_year',
            index=models.Index(fields=['year', 'is_budget'], name='scoreai_fis_year_083156_idx'),
        ),
        migrations.AddIndex(
            model_name='usercompany',
            index=models.Index(fields=['user', 'company', 'active'], name='scoreai_use_user_id_d6cb32_idx'),
        ),
        migrations.AddIndex(
            model_name='usercompany',
            index=models.Index(fields=['user', 'is_selected', 'active'], name='scoreai_use_user_id_942113_idx'),
        ),
        migrations.AddIndex(
            model_name='usercompany',
            index=models.Index(fields=['company', 'active', 'is_owner'], name='scoreai_use_company_949422_idx'),
        ),
        migrations.AddIndex(
            model_name='usercompany',
            index=models.Index(fields=['company', 'active', 'is_manager'], name='scoreai_use_company_32a369_idx'),
        ),
    ]
