# Generated by Django - Data migration to populate firm field for existing todos

from django.db import migrations


def populate_todo_firm(apps, schema_editor):
    """既存のToDoレコードにFirmを設定"""
    Todo = apps.get_model('scoreai', 'Todo')
    FirmCompany = apps.get_model('scoreai', 'FirmCompany')
    
    for todo in Todo.objects.filter(firm__isnull=True):
        if todo.company:
            # CompanyからFirmを取得（active優先）
            firm_company = FirmCompany.objects.filter(
                company=todo.company,
                active=True
            ).first()
            
            if not firm_company:
                # activeでないものも含めて検索
                firm_company = FirmCompany.objects.filter(
                    company=todo.company
                ).first()
            
            if firm_company:
                todo.firm = firm_company.firm
                todo.save()


def reverse_populate_todo_firm(apps, schema_editor):
    """Firmをクリア（逆マイグレーション用）"""
    Todo = apps.get_model('scoreai', 'Todo')
    Todo.objects.update(firm=None)


class Migration(migrations.Migration):

    dependencies = [
        ('scoreai', '0127_add_firm_to_todo'),
    ]

    operations = [
        migrations.RunPython(populate_todo_firm, reverse_populate_todo_firm),
    ]
